name: Label and Assign
on:
  pull_request:
    types: [opened, reopened]
    branches:
      - development
jobs:
  add-labels-and-assignees:
    runs-on: ubuntu-latest
    steps:
      - name: Add labels
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['bug', 'STG']
            })
      - name: Add assignees
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.addAssignees({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              reviewers: ['Suyoung225']
            })
