name: Label and Assign
on:
  pull_request:
    types: [opened, reopened]
    branches:
      - main
jobs:
  add-labels-and-assignees:
    runs-on: ubuntu-latest
    steps:
      - name: Add labels
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.ACCESS_TOKEN}}
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['bug', 'STG']
            })
      - name: Add reviewers
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.ACCESS_TOKEN}}
          script: |
            let creator = context.payload.pull_request.user.login;
            let reviewers;

            if (creator === 'Suyoung225') {
              reviewers = ['fin2b-syyun'];
            } else if (creator === 'fin2b-syyun') {
              reviewers = ['Suyoung225'];
            }

            github.pulls.requestReviewers({
              pull_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              reviewers: reviewers
            });
