name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
          cache-dependency-path: 'build.gradle.kts'
          
      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew
          
      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: cicdsample
          path: build/libs/*.jar
          
      - name: Download artifact 
        uses: actions/download-artifact@v3
        with:
          name: cicdsample
          
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Add remote server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.REMOTE_IP }} >> ~/.ssh/known_hosts
          
      - name: SCP transfer
        run: scp *.jar ${{ secrets.REMOTE_USERNAME }}@${{ secrets.REMOTE_IP }}:~/app
        
      - name: Execute remote commands
        run: |
          ssh -v ${{ secrets.REMOTE_USERNAME }}@${{ secrets.REMOTER_IP }} "sudo fuser -k 8080/tcp || true"
          ssh -v ${{ secrets.REMOTE_USERNAME }}@${{ secrets.REMOTE_IP }} "sudo nohup java -jar ~/app/*.jar  > ~/app/nohup.log 2>&1 &"
     
